### ISSUE TITLE
SQL examples from the README don't work out of the box

### ISSUE THREAD

**Issue by thoughtpolice** [kevinlawler/kerf1#18]
Hi, thanks for kerf. I was following the README and hit a snag that took a few minutes to figure out; the example:

```
n: 10**4
ids: range(1, n+1)
stamps: plus(NOW(), 1s + mapright range(n))
heartrates: 80 + rand(n, 100.0)  
labels: range(6)
lanes: take(n, join(labels, reverse labels))
running: {{id: ids, stamp: stamps, heartrate: heartrates, lane: lanes}} 
```

fails on the definition of `running`:

```
KeRF> running: {{id: ids, stamp: stamps, heartrate: heartrates, lane: lanes}}

 Unknown parse group error
```

I scratched my head about this and eventually found out the problem was the name of the `stamp` field. I couldn't understand why at first, but a few minutes of reading the manual revealed that `stamp`, like `int` & co is a type, and types all have constructors, e.g. `stamp(string(now()))` or `int(10)` or whatever. So I suspect this is just a keyword/conflict error.

Just replacing the field name `stamp` with `timestamp` fixes this nicely, though the rest of the examples need updating to follow that.

Thanks a lot for releasing kerf to the public. It's a fun and inspiring little thing!

**Comment by kevinlawler** [comment]
Oops. You are right in the diagnosis and the fix. `stamp` later became a type coercion and that tutorial was never updated.

Fixed: 27722030fbdde598d9d70fb44cd2c1fc0ccdee49

Thank you
