### ISSUE TITLE
Improve repo description to make it easily discoverable

### ISSUE THREAD

**Issue by dumblob** [kevinlawler/kerf1#25]
Describing `kerf1` as "Kerf" is not enough e.g. for seaching through "favorite/starred" repos :wink:.

**Comment by kevinlawler** [comment]
i don't know what this means

**Comment by dumblob** [comment]
https://github.com/orgs/community/discussions/22456

**Comment by kevinlawler** [comment]
thanks, updated

**Comment by dumblob** [comment]
Great description, thanks!
